require "login.msg.on_config"
require "login.msg.on_db"
require "login.msg.on_gate"
require "login.msg.on_gm"
require "functions"
local msgopt = require "msgopt"

local register_dispatcher = msgopt.register


-- register_dispatcher("S_NotifyDBServerStart",on_S_NotifyDBServerStart)
-- register_dispatcher("S_ReplyUpdateDBServerConfigByLogin",on_S_ReplyUpdateDBServerConfigByLogin)
register_dispatcher("CS_QueryMaintain",on_S_Maintain_switch)
register_dispatcher("S_ReplayPlatformId",on_S_ReplayReplayPlatformTotal)
register_dispatcher("S_ReplyPlatformRechargeSwitch",on_S_ReplyPlatformRechargeSwitch)
register_dispatcher("S_ReplyPlatformCashSwitch",on_S_ReplyPlatformCashSwitch)
register_dispatcher("S_ReplyPlatformPlayerToAgentCashSwitch",on_S_ReplyPlatformPlayerToAgentCashSwitch)
register_dispatcher("S_ReplyPlatformBankerTransferSwitch",on_S_ReplyPlatformBankerTransferSwitch)
register_dispatcher("S_ReplyGlobleIntCfg",on_S_ReplyGlobleIntCfg)
register_dispatcher("S_ReplyPlatformSwitchInfo",on_S_ReplyPlatformAllSwitchInfo)
register_dispatcher("S_UpdateGameCfg ",on_S_UpdateGameCfg)
register_dispatcher("S_ReplyPlatformAllCashSwitch",on_S_ReplyPlatformAllCashSwitch)
-- register_dispatcher("DL_VerifyAccountResult",on_dl_verify_account_result)
-- register_dispatcher("DL_RegAccount",on_dl_reg_account)
register_dispatcher("DL_RegAccount2",on_dl_reg_account2)
register_dispatcher("DL_NewNotice ",on_dl_NewNotice)
register_dispatcher("DL_DelMessage ",on_dl_DelMessage)
register_dispatcher("DL_AlipayEdit",on_dl_AlipayEdit)
register_dispatcher("WL_GMMessage ",on_wl_request_GMMessage)
register_dispatcher("DL_BankcardEdit",on_dl_BankcardEdit)
register_dispatcher("DL_CashFalseInfo ",on_dl_cashfalseinfo)
-- register_dispatcher("DL_CashReply ",on_dl_cashreply)
register_dispatcher("DL_PhoneQuery",on_dl_reg_phone_query)
-- register_dispatcher("DL_ServerConfig",on_dl_server_config)
-- register_dispatcher("DL_DBGameConfigMgr",on_dl_server_config_mgr)
register_dispatcher("LC_GetInviterInfo",on_dl_get_inviter_info)
register_dispatcher("DL_LuaCmdPlayerResult",on_DL_LuaCmdPlayerResult)
register_dispatcher("DF_ChangMoney ",on_DF_ChangMoney)
register_dispatcher("DF_Reply ",on_DF_Reply)
register_dispatcher("DL_CashFalseReply ",on_DL_CashFalseReply)
register_dispatcher("DL_ResetAlipay ",on_DL_ResetAlipay)
register_dispatcher("DL_CreateProxyAccount",on_DL_CreateProxyAccount)
register_dispatcher("S_ReplayProxyPlatformIds",on_S_ReplayProxyPlatformIds)
register_dispatcher("S_ReplyProxyInfo",on_S_ReplyProxyInfo)
register_dispatcher("DL_AgentAddPlayerMoney",on_DL_AgentAddPlayerMoney)
register_dispatcher("DL_GMChangMoney ",on_DL_GMChangMoney)
register_dispatcher("DL_ReturnAgentMoney",on_DL_ReturnAgentMoney)
-- register_dispatcher("S_UpdateGamePlayerCount",on_S_UpdateGamePlayerCount)
register_dispatcher("S_Logout",on_s_logout)
register_dispatcher("L_KickClient",on_L_KickClient)
register_dispatcher("SS_ChangeGame",on_ss_change_game)
register_dispatcher("SL_ChangeGameResult",on_SL_ChangeGameResult)
register_dispatcher("CS_RequestSms",on_cs_request_sms)
register_dispatcher("SD_BankTransfer",on_sd_bank_transfer)
register_dispatcher("S_BankTransferByGuid",on_sd_bank_transfer_by_guid)
register_dispatcher("SC_ChatPrivate",on_sc_chat_private)
-- register_dispatcher("WL_RequestGameServerInfo",on_wl_request_game_server_info)
-- register_dispatcher("SL_WebGameServerInfo",on_sl_web_game_server_info)
register_dispatcher("WF_Recharge ",on_wf_recharge)
register_dispatcher("GL_NewNotice ",on_gl_NewNotice)
register_dispatcher("SL_CashReply",on_sl_cash_false_reply)
register_dispatcher("WL_ChangeTax",on_wl_request_change_tax)
register_dispatcher("SL_ChangeTax",on_sl_change_tax_reply)
register_dispatcher("WL_ChangeMoney ",on_wl_request_gm_change_money)
register_dispatcher("WL_ChangePlayersMoney ",on_wl_request_lua_change_players_money)
register_dispatcher("WL_LuaCmdPlayerResult",on_WL_LuaCmdPlayerResult)
register_dispatcher("SL_LuaCmdPlayerResult",on_SL_LuaCmdPlayerResult)
register_dispatcher("WL_GmCommandToServer",on_WL_GmCommandToServer)
-- register_dispatcher("SL_AddMoney",on_SL_AddMoney)
register_dispatcher("SL_GameNotice",on_SL_GameNotice)
register_dispatcher("SL_RequestProxyInfo",on_SL_RequestProxyInfo)
register_dispatcher("WL_BroadcastClientUpdate ",on_wl_broadcast_gameserver_cmd)
register_dispatcher("WF_CashFalse ",on_WF_CashFalse)
register_dispatcher("SL_CC_ChangeMoney",on_SL_AT_ChangeMoney)
register_dispatcher("SL_FreezeAccount ",on_sl_FreezeAccount)
-- register_dispatcher("DL_CC_ChangeMoney ",on_DB_Request)
-- register_dispatcher("GL_GetServerCfg",on_gl_get_server_cfg)
-- register_dispatcher("CL_GetInviterInfo",on_cl_get_server_cfg)
-- register_dispatcher("GL_ReCharge ",on_dl_recharge)
register_dispatcher("FS_ChangMoneyDeal ",on_FS_ChangMoneyDeal)
register_dispatcher("CL_Login",on_cl_login)
register_dispatcher("CL_RegAccount",on_cl_reg_account)
register_dispatcher("CL_LoginBySms",on_cl_login_by_sms)
register_dispatcher("CL_Auth",on_cl_auth)