local skynet = require "skynet"
require "functions"
require "skynet.manager"
local service = require "nameservice"
local dbopt = require "dbopt"

skynet.start(function() 
    local configd = service.unique("config.1","config/main")
    skynet.name("configd",configd)

    local dbconf = dbopt.config:query("SELECT * FROM t_db_server_cfg;")
    for _,conf in pairs(dbconf) do
        service.unique("db."..tostring(conf.id),"db/main",1)
    end

    local loginconf = dbopt.config:query("SELECT * FROM t_login_server_cfg;")
    for _,conf in pairs(loginconf) do
        service.unique("login."..tostring(conf.login_id),"login/main")
    end

    local gmd = service.unique("gm","gm/main")
    skynet.name("gmd",gmd)

    local gameconf = dbopt.config:query("SELECT * FROM t_game_server_cfg WHERE is_open != 0;")
    -- dump(gameconf)

    -- service.new("game.1","game.main","lobby",1)
    -- service.new("game.20","game.main","land",20)
    -- service.new("game.12012","game.main","banker_ox",12012)
    

    for _,conf in pairs(gameconf) do
        local gamename,gameid = conf.game_name,conf.game_id
        if gamename ~= "fishing" and gamename ~= "jc_fishing" then
            service.new("game."..tostring(conf.game_id),"game.main",gamename,gameid)
        end
    end

    -- skynet.newservice("game.main","lobby",1)
    -- skynet.newservice("game.main","sanshui",15033)
    -- skynet.newservice("game.main","sanshui",15032)
    -- skynet.newservice("game.main","sanshui",15031)
    -- skynet.newservice("game.main","redblack",27001)
    -- skynet.newservice("game.main","sanshui",15022)
    -- skynet.newservice("game.main","sanshui",15023)
    -- skynet.newservice("game.main","sanshui",15024)
    -- skynet.newservice("game.main","jc_fishing",14044)
    -- skynet.newservice("game.main","jc_fishing",14043)
    -- skynet.newservice("game.main","jc_fishing",14042)
    -- skynet.newservice("game.main","jc_fishing",14041)
    -- skynet.newservice("game.main","jc_fishing",14036)
    -- skynet.newservice("game.main","jc_fishing",14035)
    -- skynet.newservice("game.main","jc_fishing",14034)
    -- skynet.newservice("game.main","jc_fishing",14033)
    -- skynet.newservice("game.main","jc_fishing",14032)
    -- skynet.newservice("game.main","jc_fishing",14031)
    -- skynet.newservice("game.main","jc_fishing",14028)
    -- skynet.newservice("game.main","jc_fishing",14027)
    -- skynet.newservice("game.main","jc_fishing",14026)
    -- skynet.newservice("game.main","jc_fishing",14025)
    -- skynet.newservice("game.main","jc_fishing",14024)
    -- skynet.newservice("game.main","jc_fishing",14023)
    -- skynet.newservice("game.main","jc_fishing",14022)
    -- skynet.newservice("game.main","jc_fishing",14021)
    -- skynet.newservice("game.main","jc_fishing",14010)
    -- skynet.newservice("game.main","jc_fishing",14009)
    -- skynet.newservice("game.main","jc_fishing",14008)
    -- skynet.newservice("game.main","jc_fishing",14007)
    -- skynet.newservice("game.main","jc_fishing",14006)
    -- skynet.newservice("game.main","jc_fishing",14005)
    -- skynet.newservice("game.main","jc_fishing",14004)
    -- skynet.newservice("game.main","jc_fishing",14003)
    -- skynet.newservice("game.main","jc_fishing",14001)
    -- skynet.newservice("game.main","jc_fishing",14002)
    -- skynet.newservice("game.main","fishing",13044)
    -- skynet.newservice("game.main","fishing",13043)
    -- skynet.newservice("game.main","fishing",13042)
    -- skynet.newservice("game.main","fishing",13041)
    -- skynet.newservice("game.main","fishing",13036)
    -- skynet.newservice("game.main","fishing",13035)
    -- skynet.newservice("game.main","fishing",13034)
    -- skynet.newservice("game.main","fishing",13033)
    -- skynet.newservice("game.main","fishing",13032)
    -- skynet.newservice("game.main","fishing",13031)
    -- skynet.newservice("game.main","fishing",13028)
    -- skynet.newservice("game.main","fishing",13027)
    -- skynet.newservice("game.main","fishing",13026)
    -- skynet.newservice("game.main","fishing",13025)
    -- skynet.newservice("game.main","fishing",13024)
    -- skynet.newservice("game.main","fishing",13023)
    -- skynet.newservice("game.main","fishing",13022)
    -- skynet.newservice("game.main","fishing",13021)
    -- skynet.newservice("game.main","fishing",13010)
    -- skynet.newservice("game.main","fishing",13009)
    -- skynet.newservice("game.main","fishing",13008)
    -- skynet.newservice("game.main","fishing",13007)
    -- skynet.newservice("game.main","fishing",13006)
    -- skynet.newservice("game.main","fishing",13005)
    -- skynet.newservice("game.main","fishing",13004)
    -- skynet.newservice("game.main","fishing",13003)
    -- skynet.newservice("game.main","fishing",13002)
    -- skynet.newservice("game.main","fishing",13001)

    -- skynet.newservice("game.main","multi_showhand",163)
    -- skynet.newservice("game.main","multi_showhand",170)
    -- skynet.newservice("game.main","multi_showhand",171)
    -- skynet.newservice("game.main","multi_showhand",140)
    -- skynet.newservice("game.main","multi_showhand",151)
    -- skynet.newservice("game.main","multi_showhand",152)
    -- skynet.newservice("game.main","multi_showhand",153)
    -- skynet.newservice("game.main","multi_showhand",160)
    -- skynet.newservice("game.main","multi_showhand",161)
    -- skynet.newservice("game.main","multi_showhand",162)
    -- skynet.newservice("game.main","classics_ox",12510)
    -- skynet.newservice("game.main","classics_ox",12511)
    -- skynet.newservice("game.main","classics_ox",12512)
    -- skynet.newservice("game.main","land",10012)
    -- skynet.newservice("game.main","land",10013)
    -- skynet.newservice("game.main","land",10014)
    -- skynet.newservice("game.main","land",10015)
    -- skynet.newservice("game.main","land",10016)
    -- skynet.newservice("game.main","land",10017)
    -- skynet.newservice("game.main","multi_showhand",141)
    -- skynet.newservice("game.main","multi_showhand",143)
    -- skynet.newservice("game.main","multi_showhand",142)
    -- skynet.newservice("game.main","multi_showhand",150)
    -- skynet.newservice("game.main","banker_ox",12005)
    -- skynet.newservice("game.main","banker_ox",12006)
    -- skynet.newservice("game.main","banker_ox",12007)
    -- skynet.newservice("game.main","banker_ox",12008)
    -- skynet.newservice("game.main","banker_ox",12009)
    -- skynet.newservice("game.main","banker_ox",12010)
    -- skynet.newservice("game.main","banker_ox",12011)
    -- skynet.newservice("game.main","banker_ox",12012)
    -- skynet.newservice("game.main","classics_ox",12501)
    -- skynet.newservice("game.main","classics_ox",12502)
    -- skynet.newservice("game.main","classics_ox",12503)
    -- skynet.newservice("game.main","classics_ox",12504)
    -- skynet.newservice("game.main","classics_ox",12505)
    -- skynet.newservice("game.main","classics_ox",12506)
    -- skynet.newservice("game.main","classics_ox",12507)
    -- skynet.newservice("game.main","classics_ox",12508)
    -- skynet.newservice("game.main","classics_ox",12509)
    -- skynet.newservice("game.main","slotma",11501)
    -- skynet.newservice("game.main","slotma",11502)
    -- skynet.newservice("game.main","slotma",11503)
    -- skynet.newservice("game.main","slotma",11504)
    -- skynet.newservice("game.main","slotma",11505)
    -- skynet.newservice("game.main","slotma",11506)
    -- skynet.newservice("game.main","slotma",11507)
    -- skynet.newservice("game.main","slotma",11508)
    -- skynet.newservice("game.main","slotma",11509)
    -- skynet.newservice("game.main","banker_ox",12001)
    -- skynet.newservice("game.main","banker_ox",12002)
    -- skynet.newservice("game.main","banker_ox",12003)
    -- skynet.newservice("game.main","banker_ox",12004)
    -- skynet.newservice("game.main","zhajinhua",10504)
    -- skynet.newservice("game.main","zhajinhua",10505)
    -- skynet.newservice("game.main","zhajinhua",10506)
    -- skynet.newservice("game.main","zhajinhua",10507)
    -- skynet.newservice("game.main","zhajinhua",10508)
    -- skynet.newservice("game.main","ox",11001)
    -- skynet.newservice("game.main","ox",11002)
    -- skynet.newservice("game.main","land",10003)
    -- skynet.newservice("game.main","land",10004)
    -- skynet.newservice("game.main","land",10005)
    -- skynet.newservice("game.main","land",10006)
    -- skynet.newservice("game.main","land",10007)
    -- skynet.newservice("game.main","land",10008)
    -- skynet.newservice("game.main","land",10009)
    -- skynet.newservice("game.main","land",10010)
    -- skynet.newservice("game.main","land",10011)
    -- skynet.newservice("game.main","zhajinhua",10501)
    -- skynet.newservice("game.main","zhajinhua",10502)
    -- skynet.newservice("game.main","zhajinhua",10503)
    -- skynet.newservice("game.main","banker_ox",112)
    -- skynet.newservice("game.main","banker_ox",113)
    -- skynet.newservice("game.main","banker_ox",114)
    -- skynet.newservice("game.main","banker_ox",115)
    -- skynet.newservice("game.main","land",24)
    -- skynet.newservice("game.main","land",25)
    -- skynet.newservice("game.main","land",26)
    -- skynet.newservice("game.main","land",27)
    -- skynet.newservice("game.main","zhajinhua",36)
    -- skynet.newservice("game.main","classics_ox",122)
    -- skynet.newservice("game.main","classics_ox",123)
    -- skynet.newservice("game.main","classics_ox",124)
    -- skynet.newservice("game.main","classics_ox",125)
    -- skynet.newservice("game.main","land",10001)
    -- skynet.newservice("game.main","land",10002)
    -- skynet.newservice("game.main","sanshui",15005)
    -- skynet.newservice("game.main","ox",50)
    -- skynet.newservice("game.main","ox",51)
    -- skynet.newservice("game.main","slotma",90)
    -- skynet.newservice("game.main","slotma",91)
    -- skynet.newservice("game.main","slotma",92)
    -- skynet.newservice("game.main","sanshui",15001)
    -- skynet.newservice("game.main","zhajinhua",31)
    -- skynet.newservice("game.main","zhajinhua",32)
    -- skynet.newservice("game.main","zhajinhua",33)
    -- skynet.newservice("game.main","zhajinhua",34)
    -- skynet.newservice("game.main","zhajinhua",35)
    -- skynet.newservice("game.main","sanshui",15002)
    -- skynet.newservice("game.main","sanshui",15021)
    -- skynet.newservice("game.main","land",22)
    -- skynet.newservice("game.main","land",23)
    -- skynet.newservice("game.main","sanshui",15004)
    -- skynet.newservice("game.main","land",20)
    -- skynet.newservice("game.main","land",21)
    -- skynet.newservice("game.main","sanshui",15003)
    -- skynet.newservice("game.main","sanshui",15041)
    -- skynet.newservice("game.main","sanshui",15042)
    -- skynet.newservice("game.main","shaibao",31001)
    -- skynet.newservice("game.main","twenty_one",32001)
    -- skynet.newservice("game.main","toradora",4101)
    -- skynet.newservice("game.main","zhajinhua",30)
    -- skynet.newservice("game.main","fivestar",4001)
    -- skynet.newservice("game.main","showhand",40)
    -- skynet.newservice("game.main","maajan",33001)
end)
