local pb = require "pb_files"

local ACTION = {
	NONE = pb.enum("PDK_ACTION", "ACTION_NONE"),
	DISCARD = pb.enum("PDK_ACTION", "ACTION_DISCARD"),
	PASS = pb.enum("PDK_ACTION", "ACTION_PASS"),
}

local CARDS_TYPE = {
	SINGLE = pb.enum("PDK_CARD_TYPE", "SINGLE"),
	LAIZI_SINGLE = pb.enum("PDK_CARD_TYPE", "LAIZI_SINGLE"),
	DOUBLE = pb.enum("PDK_CARD_TYPE", "DOUBLE"),
	LAIZI_DOUBLE = pb.enum("PDK_CARD_TYPE", "LAIZI_DOUBLE"),
	THREE = pb.enum("PDK_CARD_TYPE", "THREE"),
	LAIZI_THREE = pb.enum("PDK_CARD_TYPE", "LAIZI_THREE"),
	THREE_WITH_ONE = pb.enum("PDK_CARD_TYPE", "THREE_WITH_ONE"),
	THREE_WITH_TWO = pb.enum("PDK_CARD_TYPE", "THREE_WITH_TWO"),
	FOUR_WITH_SINGLE = pb.enum("PDK_CARD_TYPE", "FOUR_WITH_SINGLE"),
	FOUR_WITH_DOUBLE = pb.enum("PDK_CARD_TYPE", "FOUR_WITH_DOUBLE"),
	SINGLE_LINE = pb.enum("PDK_CARD_TYPE", "SINGLE_LINE"),
	DOUBLE_LINE = pb.enum("PDK_CARD_TYPE", "DOUBLE_LINE"),
	PLANE = pb.enum("PDK_CARD_TYPE", "PLANE"),
	PLANE_WITH_ONE = pb.enum("PDK_CARD_TYPE", "PLANE_WITH_ONE"),
	PLANE_WITH_TWO = pb.enum("PDK_CARD_TYPE", "PLANE_WITH_TWO"),
	BOMB = pb.enum("PDK_CARD_TYPE", "BOMB"),
	FOUR_WITH_THREE = pb.enum("PDK_CARD_TYPE", "FOUR_WITH_THREE"),
	SOFT_TRIPLE_BOMB = pb.enum("PDK_CARD_TYPE","SOFT_TRIPLE_BOMB"),
	SOFT_BOMB  = pb.enum("PDK_CARD_TYPE","SOFT_BOMB"),
	TRIPLE_BOMB = pb.enum("PDK_CARD_TYPE","TRIPLE_BOMB"),
	LAIZI_BOMB = pb.enum("PDK_CARD_TYPE","LAIZI_BOMB"),
	LAIZI_TRIPLE_BOMB = pb.enum("PDK_CARD_TYPE","LAIZI_TRIPLE_BOMB"),
	FOUR = pb.enum("PDK_CARD_TYPE","FOUR"),
	LAIZI_FOUR = pb.enum("PDK_CARD_TYPE","LAIZI_FOUR"),
	MISSLE = pb.enum("PDK_CARD_TYPE", "MISSLE"),
}

return {
	ACTION = ACTION,
	CARDS_TYPE = CARDS_TYPE,
}