local pb = require "pb_files"
local log = require "log"

local CARDS_TYPE = {
	CT235 = pb.enum("ZHAJINHUA_CARD_TYPE", "ZHAJINHUA_CARD_TYPE_235"),
	SINGLE = pb.enum("ZHAJINHUA_CARD_TYPE", "ZHAJINHUA_CARD_TYPE_SINGLE"),
	DOUBLE = pb.enum("ZHAJINHUA_CARD_TYPE", "ZHAJINHUA_CARD_TYPE_DOUBLE"),
	SHUN_ZI = pb.enum("ZHAJINHUA_CARD_TYPE", "ZHAJINHUA_CARD_TYPE_SHUN_ZI"),
	JIN_HUA = pb.enum("ZHAJINHUA_CARD_TYPE", "ZHAJINHUA_CARD_TYPE_JIN_HUA"),
	SHUN_JIN = pb.enum("ZHAJINHUA_CARD_TYPE", "ZHAJINHUA_CARD_TYPE_SHUN_JIN"),
	BAO_ZI = pb.enum("ZHAJINHUA_CARD_TYPE", "ZHAJINHUA_CARD_TYPE_BAO_ZI"),
}

local TABLE_STATUS = {
	-- 等待开始
	FREE = pb.enum("ZHAJINHUA_TABLE_STATUS","TS_FREE"),
	-- 游戏进行
	PLAY = pb.enum("ZHAJINHUA_TABLE_STATUS","TS_PLAY"),
	END = pb.enum("ZHAJINHUA_TABLE_STATUS","TS_END"),
}

local PLAYER_STATUS = {
	WATCHER = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_WATHER"),	   --旁观
    FREE = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_FREE"),		   --空闲
    READY = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_READY"),         -- 准备
    WAIT = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_WAIT"),           -- 等待下注
    CONTROL = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_CONTROL"),     -- 准备操作
    LOOK = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_LOOK"),           -- 看牌
    COMPARE = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_COMPARE"),     -- 比牌
    DROP = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_DROP"),           -- 弃牌
    LOSE = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_LOSE"),           -- 淘汰
    EXIT = pb.enum("ZHAJINHUA_PLAYER_STATUS","PS_EXIT"),           -- 离开
}

local ACTION = {
	NONE = pb.enum("ZHAJINHUA_ACTION", "ZHAJINHUA_ACTION_NONE"),
	ADD_SCORE = pb.enum("ZHAJINHUA_ACTION", "ZHAJINHUA_ACTION_ADD_SCORE"),
	DROP = pb.enum("ZHAJINHUA_ACTION", "ZHAJINHUA_ACTION_DROP"),
	PASS = pb.enum("ZHAJINHUA_ACTION", "ZHAJINHUA_ACTION_PASS"),
	FOLLOW = pb.enum("ZHAJINHUA_ACTION", "ZHAJINHUA_ACTION_FOLLOW"),
	LOOK_CARDS = pb.enum("ZHAJINHUA_ACTION", "ZHAJINHUA_ACTION_LOOK_CARDS"),
	ALL_IN = pb.enum("ZHAJINHUA_ACTION", "ZHAJINHUA_ACTION_ALL_IN"),
	COMPARE = pb.enum("ZHAJINHUA_ACTION", "ZHAJINHUA_ACTION_COMPARE"),
}

return {
    CARDS_TYPE = CARDS_TYPE,
    TABLE_STATUS = TABLE_STATUS,
	PLAYER_STATUS = PLAYER_STATUS,
	ACTION = ACTION,
}