root = "./"
luaservice = root.."common/?.lua;"..root.."geek/script/?.lua;"..root.."common/service/?.lua;"..root.."geek/script/service/?.lua;"..root.."service/?.lua;"
lualoader = root.."common/loader.lua"
lua_path = "./?.lua;"..root.."common/?.lua;"..root.."lualib/?.lua;"..root.."lualib/?/init.lua;"..root.."geek/script/?.lua;"..root.."geek/?.lua"
lua_cpath = root.."common/luaclib/?.so;"..root .. "luaclib/?.so;"..root .. "geek/luaclib/?.so"
snax = "./?.lua;"..root.."common/?.lua;"..root.."geek/script/?.lua;"..root.."geek/?.lua"
