local pb = require "pb_files"

--没有牌型
Not_This_Card_Type = 0


Special_cards_type = {}

--特殊牌型
Special_cards_type.THIRTEEN_SPECIAL_THREE_TONG_HUA     = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_THREE_TONG_HUA")
Special_cards_type.THIRTEEN_SPECIAL_THREE_SHUN_ZI      = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_THREE_SHUN_ZI")
Special_cards_type.THIRTEEN_SPECIAL_SIX_DOUBLE         = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_SIX_DOUBLE")
Special_cards_type.THIRTEEN_SPECIAL_FIVE_DOUBLE_THREE  = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_FIVE_DOUBLE_THREE")
Special_cards_type.THIRTEEN_SPECIAL_FOUR_THREE         = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_FOUR_THREE")
Special_cards_type.THIRTEEN_SPECIAL_SAME_COLOR 		   = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_SAME_COLOR")
Special_cards_type.THIRTEEN_SPECIAL_ALL_SMALL          = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_ALL_SMALL")
Special_cards_type.THIRTEEN_SPECIAL_ALL_BIG            = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_ALL_BIG")
Special_cards_type.THIRTEEN_SPECIAL_THREE_FOUR         = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_THREE_FOUR")
Special_cards_type.THIRTEEN_SPECIAL_THREE_TONGHUA_SHUN = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_THREE_TONGHUA_SHUN")
Special_cards_type.THIRTEEN_SPECIAL_ALL_AKQJ           = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_ALL_AKQJ")
Special_cards_type.THIRTEEN_SPECIAL_LONG               = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_LONG")
Special_cards_type.THIRTEEN_SPECIAL_QING_LONG          = pb.enum("THIRTEEN_SPECIAL_CARD_TYPE", "THIRTEEN_SPECIAL_QING_LONG")


Cards_type = {}

--普通牌类型
Cards_type.THIRTEEN_CARD_TYPE_WULONG          = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_WULONG")
Cards_type.THIRTEEN_CARD_TYPE_DOUBLE          = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_DOUBLE")
Cards_type.THIRTEEN_CARD_TYPE_DOUBLE_TWO      = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_DOUBLE_TWO")
Cards_type.THIRTEEN_CARD_TYPE_THREE           = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_THREE")
Cards_type.THIRTEEN_CARD_TYPE_SHUN_ZI         = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_SHUN_ZI")
Cards_type.THIRTEEN_CARD_TYPE_TONG_HUA        = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_TONG_HUA")
Cards_type.THIRTEEN_CARD_TYPE_HULU            = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_HULU")
Cards_type.THIRTEEN_CARD_TYPE_MIDDLE_HULU     = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_MIDDLE_HULU")
Cards_type.THIRTEEN_CARD_TYPE_FOUR            = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_FOUR")
Cards_type.THIRTEEN_CARD_TYPE_TONG_HUA_SHUN   = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_TONG_HUA_SHUN")
Cards_type.THIRTEEN_CARD_TYPE_CHONG_SAN       = pb.enum("THIRTEEN_CARD_TYPE", "THIRTEEN_CARD_TYPE_CHONG_SAN")