local log = require "log"
require "table_func"
require "functions"

local pb = require "pb"

local LOGIN_RESULT_LOGIN_QUQUE = pb.enum("LOGIN_RESULT","LOGIN_RESULT_LOGIN_QUQUE")
local LOGIN_RESULT_ACCOUNT_PASSWORD_ERR = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_ACCOUNT_PASSWORD_ERR")
local LOGIN_RESULT_SMS_FAILED = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_SMS_FAILED")
local LOGIN_RESULT_SAME_PASSWORD = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_SAME_PASSWORD")
local LOGIN_RESULT_SMS_ERR = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_SMS_ERR")
local LOGIN_RESULT_ACCOUNT_CHAR_LIMIT = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_ACCOUNT_CHAR_LIMIT")
local LOGIN_RESULT_ACCOUNT_SIZE_LIMIT = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_ACCOUNT_SIZE_LIMIT")
local LOGIN_RESULT_SET_ACCOUNT_OR_PASSWORD_EMPTY = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_SET_ACCOUNT_OR_PASSWORD_EMPTY")
local LOGIN_RESULT_NICKNAME_LIMIT = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_NICKNAME_LIMIT")
local LOGIN_RESULT_NICKNAME_EMPTY = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_NICKNAME_EMPTY")
local LOGIN_RESULT_POTATO_CHECK_ERROR = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_POTATO_CHECK_ERROR")
local LOGIN_RESULT_TEL_ERR = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_TEL_ERR")
local LOGIN_RESULT_TEL_LEN_ERR = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_TEL_LEN_ERR")
local LOGIN_RESULT_SMS_REPEATED = pb.enum("LOGIN_RESULT", "LOGIN_RESULT_SMS_REPEATED")

local m_potato_https_curl = ""
local m_potato_login_access_token = ""
local m_potato_key = ""
local potato_url = "https:--oauth.potato.im:8443/oauth2/api/userinfo"

